analyzer:
  errors:
    deprecated_member_use: ignore
    include_file_not_found: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_declarations: true
    avoid_print: true
