"""Curriculum definition for FluentSoul.

Two tracks:
  TRACK A - "Unfreeze"     -> for users who understand English but blank when speaking
  TRACK B - "From Scratch" -> for true beginners with little/no English

Track B feeds directly into Track A (last week is a bridge, not a separate app experience).

Every day is built around the loop:
  Shadow/Listen (optional runway) -> Mood check-in (optional) -> Speak -> Rescue phrase if blank -> Reflect
"""

from typing import Any, Dict, List, Optional

# ---------------------------------------------------------------------------
# PERSONAS
# ---------------------------------------------------------------------------

PERSONAS_INFO: Dict[str, Dict[str, Any]] = {
    "riya": {
        "name": "Riya",
        "initial": "R",
        "color": "#FF8B5E",
        "sub": "🇮🇳 Empathetic Peacemaker",
        "flag": "🇮🇳",
    },
    "rohan": {
        "name": "Rohan",
        "initial": "R",
        "color": "#E3B23C",
        "sub": "🇮🇳 Structured Strategist",
        "flag": "🇮🇳",
    },
    "emily": {
        "name": "Emily",
        "initial": "E",
        "color": "#F0455C",
        "sub": "🇺🇸 Sharp Orator",
        "flag": "🇺🇸",
    },
    "alex": {
        "name": "Alex",
        "initial": "A",
        "color": "#9B7CF2",
        "sub": "🇺🇸 Analytical Contrarian",
        "flag": "🇺🇸",
    },
    "panel": {
        "name": "Group Room",
        "initial": "◆",
        "color": "#3FC1A8",
        "sub": "Riya · Rohan · Emily · Alex",
        "flag": "🌐",
    },
}

# Rescue phrases are available on EVERY foundation/milestone day in Track A so a user
# always has an escape hatch instead of going silent. Defined once, reused everywhere.
DEFAULT_RESCUE_PHRASES: List[str] = [
    "Give me a sec...",
    "Let me think about that...",
    "How do I say this...",
    "Hmm, good question...",
]

# Lighter version for beginners (Track B) - shorter, easier to physically say
BEGINNER_RESCUE_PHRASES: List[str] = [
    "Wait, please...",
    "One moment...",
    "I think... umm...",
]

MOOD_OPTIONS: List[str] = ["😰 Nervous", "😐 Neutral", "😊 Confident"]


# ---------------------------------------------------------------------------
# TRACK A — "UNFREEZE" (30 days, + Day 0 onboarding)
# For users who understand English but blank when speaking.
# ---------------------------------------------------------------------------

TRACK_A_WEEKS: List[Dict[str, Any]] = [
    {
        "title": "Day 0 · Freeze Protocol",
        "range": "Onboarding",
        "days": [
            {
                "d": 0,
                "theme": "Learn Your Rescue Phrases",
                "persona": "riya",
                "mode": "onboarding",
                "aiLine": "Before we speak a single word of English together, I want to give you a safety net. Everyone blanks sometimes — even native speakers. The difference is what you do in that moment.",
                "instruction": "Listen to Riya say each rescue phrase, repeat it out loud once, and save your favorite one as your 'go-to.' You will not be graded today.",
                "phrasesA": [],
                "phrasesB": [],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "Give me a sec... Let me think about that... How do I say this...",
                "moodCheckIn": True,
                "script": [
                    "Riya: If you ever go blank, just say 'Give me a sec' — that buys you time and keeps the conversation alive.",
                    "You: (repeat the phrase back)",
                ],
                "wpm": None,
                "filler": "n/a",
                "milestoneReport": False,
            }
        ],
    },
    {
        "title": "Warm-Up · Break the Silence",
        "range": "Days 1–7",
        "days": [
            {
                "d": 1,
                "theme": "Introduce Yourself",
                "persona": "riya",
                "mode": "foundation",
                "aiLine": "Hey! I'm Riya. Before we jump in — just tell me who you are. Don't rehearse it, just talk.",
                "instruction": "Tap the mic and introduce yourself for 30 seconds. Say your name, where you're from, and one thing you like. No perfect grammar needed.",
                "phrasesA": ["I'm from...", "One thing about me is...", "I enjoy..."],
                "phrasesB": ["I am...", "My name is...", "I am from...", "Nice to meet you"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "Hi, I'm Riya. I'm from Bengaluru, and I enjoy long walks.",
                "moodCheckIn": True,
                "script": ["Riya: What should I call you?", "You: I'm Aditya, I'm from Pune."],
                "wpm": 80,
                "filler": "≤6/min",
            },
            {
                "d": 2,
                "theme": "Daily Routine",
                "persona": "riya",
                "mode": "foundation",
                "aiLine": "Walk me through your morning — start from the moment you wake up.",
                "instruction": "Describe your daily routine out loud. Use present tense. Try for 5 sentences without stopping.",
                "phrasesA": ["Right after I wake up...", "Before I leave for work..."],
                "phrasesB": ["I wake up at...", "I eat breakfast", "I go to...", "I sleep at..."],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "Right after I wake up, I check my phone and make tea.",
                "moodCheckIn": False,
                "script": ["Riya: What's the first thing you do after waking up?", "You: I check my phone, then I make tea."],
                "wpm": 82,
                "filler": "≤6/min",
            },
            {
                "d": 3,
                "theme": "Family & People",
                "persona": "riya",
                "mode": "foundation",
                "aiLine": "Tell me about someone important in your life.",
                "instruction": "Pick 3 people close to you. Describe each one in 2–3 sentences — who they are and one thing about them.",
                "phrasesA": ["What stands out about them is...", "We're close because..."],
                "phrasesB": ["This is my...", "He is...", "She is...", "We live together"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "This is my sister — she's funny and very supportive.",
                "moodCheckIn": False,
                "script": ["Riya: Who's someone you talk to every day?", "You: My sister — she is funny and very supportive."],
                "wpm": 84,
                "filler": "≤5/min",
            },
            {
                "d": 4,
                "theme": "Likes & Dislikes",
                "persona": "riya",
                "mode": "foundation",
                "aiLine": "What do you love? And what can you totally skip?",
                "instruction": "Share 3 things you like and 3 you don't — and give a quick reason for each.",
                "phrasesA": ["What I really enjoy is...", "I could do without..."],
                "phrasesB": ["I like...", "I don't like...", "...because"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "I like tea. I don't like coffee — it's too strong for me.",
                "moodCheckIn": False,
                "script": ["Riya: Coffee or tea?", "You: Tea — I don't like coffee, it's too strong for me."],
                "wpm": 86,
                "filler": "≤5/min",
            },
            {
                "d": 5,
                "theme": "Numbers & Time",
                "persona": "riya",
                "mode": "foundation",
                "aiLine": "Quick fire round — tell me your phone number, no pausing between digits.",
                "instruction": "Say your age, phone number, and today's date out loud without hesitating.",
                "phrasesA": ["It's currently...", "My number is..."],
                "phrasesB": ["Numbers 1–100", "It's... o'clock", "Today is..."],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "It's currently nine thirty in the morning.",
                "moodCheckIn": False,
                "script": ["Riya: What time do you usually start work?", "You: Around nine thirty in the morning."],
                "wpm": 88,
                "filler": "≤5/min",
            },
            {
                "d": 6,
                "theme": "Asking Questions",
                "persona": "riya",
                "mode": "foundation",
                "aiLine": "Your turn — ask me three questions about myself.",
                "instruction": "Ask Riya 3 questions using What, Where, or How. Listen to her answer before asking the next.",
                "phrasesA": ["Can I ask you something?", "What made you..."],
                "phrasesB": ["What...", "Where...", "When...", "Who...", "How..."],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "Can I ask you something — where are you from?",
                "moodCheckIn": False,
                "script": ["You: Where are you from, Riya?", "Riya: I'm based in Bengaluru! Your turn to ask another."],
                "wpm": 90,
                "filler": "≤4/min",
            },
            {
                "d": 7,
                "theme": "Milestone: The 60-Second Intro",
                "persona": "riya",
                "mode": "milestone",
                "aiLine": "Give me your best 60 seconds. I'm recording this one for your report.",
                "instruction": "Introduce yourself for a full 60 seconds — no script, no notes. This recording becomes your Week 1 baseline.",
                "phrasesA": ["(no scaffold — speak freely)"],
                "phrasesB": ["Use any phrases from Day 1–6"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": True,
                "script": ["Riya: Ready when you are — just press and talk.", "You: (60-second free response)"],
                "wpm": 92,
                "filler": "≤4/min",
                "milestoneReport": True,
            },
        ],
    },
    {
        "title": "Form & Technique · Build Real Sentences",
        "range": "Days 8–14",
        "days": [
            {
                "d": 8,
                "theme": "Food & Ordering",
                "persona": "rohan",
                "mode": "foundation",
                "aiLine": "Let's structure this: greeting, order, one follow-up question. Ready to order?",
                "instruction": "Roleplay ordering food at a restaurant. Greet, place your order, then answer Rohan's follow-up.",
                "phrasesA": ["I'll have the...", "Could I also get...", "Actually, can you make that..."],
                "phrasesB": ["I would like...", "Can I get...", "For here or to go"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "I'll have the coffee, and could I also get a sandwich?",
                "moodCheckIn": False,
                "script": ["Rohan: What can I get you today?", "You: I'd like a coffee and a sandwich, please."],
                "wpm": 94,
                "filler": "≤4/min",
            },
            {
                "d": 9,
                "theme": "Directions",
                "persona": "rohan",
                "mode": "foundation",
                "aiLine": "Break it into three steps — where you are, where you're going, how to get there.",
                "instruction": "Give Rohan directions to a place near you. Then ask him for directions somewhere.",
                "phrasesA": ["Head towards...", "You can't miss it", "It's just past the..."],
                "phrasesB": ["Turn left", "Turn right", "Go straight", "It's next to..."],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "Go straight, then turn left. You can't miss it.",
                "moodCheckIn": False,
                "script": ["Rohan: How do I get to the station from here?", "You: Go straight, then turn left at the signal."],
                "wpm": 96,
                "filler": "≤4/min",
            },
            {
                "d": 10,
                "theme": "Shopping",
                "persona": "rohan",
                "mode": "foundation",
                "aiLine": "Let's map the negotiation — ask the price, counter it, then confirm.",
                "instruction": "Roleplay buying something. Ask the price, try negotiating once, then agree on a final price.",
                "phrasesA": ["Is that the best you can do?", "I'll take it for..."],
                "phrasesB": ["How much is this?", "Can I get a discount?", "I'll take it"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "Is that the best you can do? I'll take it for four hundred.",
                "moodCheckIn": False,
                "script": ["Rohan: That'll be 500 rupees.", "You: Can you do 400? I'll take two."],
                "wpm": 98,
                "filler": "≤3/min",
            },
            {
                "d": 11,
                "theme": "Weather & Small Talk",
                "persona": "rohan",
                "mode": "foundation",
                "aiLine": "Structured small talk still needs a plan — opener, comment, question back.",
                "instruction": "Make small talk with Rohan for 1 minute. Comment on the weather, then ask him a question back.",
                "phrasesA": ["Can you believe this weather?", "How's your day going so far?"],
                "phrasesB": ["It is hot/cold/sunny", "Nice weather today"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "Can you believe this weather? How's your day going so far?",
                "moodCheckIn": False,
                "script": ["Rohan: It's really humid today, isn't it?", "You: Yes, definitely. Do you like this season?"],
                "wpm": 100,
                "filler": "≤3/min",
            },
            {
                "d": 12,
                "theme": "Past Tense Stories",
                "persona": "rohan",
                "mode": "foundation",
                "aiLine": "Sequence it for me — what happened first, next, and last?",
                "instruction": "Tell Rohan 3 things you did yesterday, in order, using past tense.",
                "phrasesA": ["Right after that, I...", "By the end of the day..."],
                "phrasesB": ["I worked", "I watched", "I called", "I walked"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "Right after that, I called my friend, and by the end of the day I was tired.",
                "moodCheckIn": False,
                "script": ["Rohan: What did you do yesterday evening?", "You: I finished work, then I called my friend."],
                "wpm": 102,
                "filler": "≤3/min",
            },
            {
                "d": 13,
                "theme": "Future Plans",
                "persona": "rohan",
                "mode": "foundation",
                "aiLine": "Structure your plan — goal, steps, timeline.",
                "instruction": "Tell Rohan your plan for this weekend. Include at least 2 things you'll do.",
                "phrasesA": ["My plan is to...", "I'm hoping to..."],
                "phrasesB": ["I will...", "I am going to..."],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "My plan is to visit my parents, and I'm hoping to rest too.",
                "moodCheckIn": False,
                "script": ["Rohan: Any plans this weekend?", "You: I'm going to visit my parents on Saturday."],
                "wpm": 104,
                "filler": "≤3/min",
            },
            {
                "d": 14,
                "theme": "Milestone: First Group Discussion",
                "persona": "panel",
                "mode": "milestone",
                "aiLine": "Three pillars today — your ideas, your evidence, your turn-taking. Riya and I are both in the room.",
                "instruction": "Join a 2-minute group discussion with Riya and Rohan on a simple topic. Take at least 2 turns.",
                "phrasesA": ["(no scaffold — speak freely)"],
                "phrasesB": ["Use any phrases from Week 1–2"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": True,
                "script": ["Rohan: Let's discuss — is remote work better than office work?", "Riya: I'd love to hear your take first!"],
                "wpm": 106,
                "filler": "≤3/min",
                "milestoneReport": True,
            },
        ],
    },
    {
        "title": "Sparring · Real Conversations",
        "range": "Days 15–21",
        "days": [
            {
                "d": 15,
                "theme": "Phone Calls",
                "persona": "emily",
                "mode": "foundation",
                "aiLine": "Confidence starts with your opening line. Let's hear it — the phone's ringing.",
                "instruction": "Roleplay answering and making a phone call with Emily. Open, respond, and close politely.",
                "phrasesA": ["Speaking, how can I help?", "Could you repeat that, please?"],
                "phrasesB": ["Hello, this is...", "Can I take a message?"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "Speaking, how can I help? Could you repeat that, please?",
                "moodCheckIn": False,
                "script": ["Emily: Hi, is this Aditya?", "You: Yes, speaking. How can I help you?"],
                "wpm": 108,
                "filler": "≤3/min",
            },
            {
                "d": 16,
                "theme": "Job Interview Basics",
                "persona": "emily",
                "mode": "foundation",
                "aiLine": "Tell me about yourself — and make me remember it.",
                "instruction": "Answer 2 common interview questions from Emily in under 60 seconds each.",
                "phrasesA": ["What sets me apart is...", "I'm particularly proud of..."],
                "phrasesB": ["I have experience in...", "My strengths are..."],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "What sets me apart is my ability to learn fast.",
                "moodCheckIn": True,
                "script": ["Emily: Why should we hire you?", "You: I bring strong problem-solving skills and I learn fast."],
                "wpm": 110,
                "filler": "≤2/min",
            },
            {
                "d": 17,
                "theme": "Expressing Opinions",
                "persona": "emily",
                "mode": "foundation",
                "aiLine": "I disagree — convince me otherwise.",
                "instruction": "Pick a simple topic. State your opinion, then respond when Emily pushes back.",
                "phrasesA": ["I see it differently because...", "That's fair, but consider..."],
                "phrasesB": ["I think...", "In my opinion..."],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "I see it differently because it also removes commute stress.",
                "moodCheckIn": False,
                "script": ["Emily: I think remote work hurts collaboration.", "You: I see your point, but it also removes commute stress."],
                "wpm": 112,
                "filler": "≤2/min",
            },
            {
                "d": 18,
                "theme": "Problem Solving & Complaints",
                "persona": "emily",
                "mode": "foundation",
                "aiLine": "Stay calm — state the problem, then propose the fix.",
                "instruction": "Roleplay a complaint call. Explain the issue clearly and ask for a solution.",
                "phrasesA": ["Here's exactly what happened...", "What I'd like is..."],
                "phrasesB": ["There is a problem with...", "Can you help me fix..."],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "Here's exactly what happened — my order arrived damaged.",
                "moodCheckIn": False,
                "script": ["Emily: What seems to be the issue?", "You: There's a problem with my order — it arrived damaged."],
                "wpm": 114,
                "filler": "≤2/min",
            },
            {
                "d": 19,
                "theme": "Emotions & Feelings",
                "persona": "emily",
                "mode": "foundation",
                "aiLine": "Good and bad are boring words — give me something sharper.",
                "instruction": "Describe how you feel today using 3 different feeling words, and explain why for each.",
                "phrasesA": ["I'm a bit overwhelmed because...", "Honestly, I feel relieved that..."],
                "phrasesB": ["I feel happy", "I feel tired", "I feel worried"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "Honestly, I feel a little tired, but hopeful about the weekend.",
                "moodCheckIn": True,
                "script": ["Emily: How are you feeling about this week?", "You: A little tired, but hopeful about the weekend."],
                "wpm": 116,
                "filler": "≤2/min",
            },
            {
                "d": 20,
                "theme": "Travel English",
                "persona": "emily",
                "mode": "foundation",
                "aiLine": "Handle the whole check-in. Don't let me throw you off.",
                "instruction": "Roleplay a hotel check-in from greeting to getting your room key.",
                "phrasesA": ["I have a reservation under...", "Is breakfast included?"],
                "phrasesB": ["I'd like to check in", "Here is my ID"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "I have a reservation under Aditya Sharma. Is breakfast included?",
                "moodCheckIn": False,
                "script": ["Emily: Welcome! Do you have a reservation?", "You: Yes, it's under Aditya Sharma."],
                "wpm": 118,
                "filler": "≤2/min",
            },
            {
                "d": 21,
                "theme": "Milestone: Free Conversation",
                "persona": "emily",
                "mode": "milestone",
                "aiLine": "Surprise topic, no prep. Go.",
                "instruction": "Have a free 3-minute conversation with Emily on a topic she picks. No scaffolding this time.",
                "phrasesA": ["(no scaffold — speak freely)"],
                "phrasesB": ["Use any phrases from Week 3"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": True,
                "script": ["Emily: Let's talk about something unexpected — favorite childhood memory?", "You: (free response)"],
                "wpm": 120,
                "filler": "≤2/min",
                "milestoneReport": True,
            },
        ],
    },
    {
        "title": "Competition Pace · Spontaneity & Debate",
        "range": "Days 22–28",
        "days": [
            {
                "d": 22,
                "theme": "Random Topic Speaking",
                "persona": "alex",
                "mode": "debate",
                "aiLine": "What if I hand you a topic you've never thought about? Talk anyway.",
                "instruction": "Alex will give you a random topic. Speak for 60 seconds with zero prep time.",
                "phrasesA": ["My initial reaction is...", "Thinking about it more..."],
                "phrasesB": ["I think... because...", "One example is..."],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": False,
                "script": ["Alex: Should schools teach coding from age 5?", "You: (60-second impromptu response)"],
                "wpm": 122,
                "filler": "≤2/min",
            },
            {
                "d": 23,
                "theme": "Debate & Disagree Politely",
                "persona": "alex",
                "mode": "debate",
                "aiLine": "Challenge the core assumption — why must it be true?",
                "instruction": "Take a side in a mini-debate with Alex. Defend it for 2 exchanges.",
                "phrasesA": ["That assumes... but what if...", "I'd push back on..."],
                "phrasesB": ["I see your point, but...", "I disagree because..."],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": False,
                "script": ["Alex: Social media does more harm than good — agree?", "You: I see your point, but it also connects people globally."],
                "wpm": 124,
                "filler": "≤1/min",
            },
            {
                "d": 24,
                "theme": "Storytelling",
                "persona": "alex",
                "mode": "debate",
                "aiLine": "Give me structure — setup, tension, resolution.",
                "instruction": "Tell Alex a 1-minute personal story with a clear beginning, middle, and end.",
                "phrasesA": ["It all started when...", "In the end..."],
                "phrasesB": ["First...", "Then...", "Finally..."],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": False,
                "script": ["Alex: Tell me about a time something went wrong.", "You: It all started when I missed my train..."],
                "wpm": 126,
                "filler": "≤1/min",
            },
            {
                "d": 25,
                "theme": "Presenting an Idea",
                "persona": "alex",
                "mode": "debate",
                "aiLine": "Pitch it in 90 seconds. I'm timing you.",
                "instruction": "Pitch one idea to Alex in under 90 seconds. State the idea, why it matters, and one next step.",
                "phrasesA": ["The core idea is...", "Here's why this matters..."],
                "phrasesB": ["I want to talk about...", "My idea is..."],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": False,
                "script": ["Alex: What's your idea?", "You: I want to talk about a way to reduce commute time for teams."],
                "wpm": 128,
                "filler": "≤1/min",
            },
            {
                "d": 26,
                "theme": "Handling Interruptions",
                "persona": "alex",
                "mode": "debate",
                "aiLine": "I'm going to cut you off mid-sentence. Recover.",
                "instruction": "Answer Alex's question. He'll interrupt you once — pick your sentence back up smoothly using a rescue phrase if needed.",
                "phrasesA": ["As I was saying...", "Let me just finish this point..."],
                "phrasesB": ["Sorry, let me finish", "Can I continue?"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": False,
                "script": ["Alex: Wait, that can't be — (interrupts)", "You: Sorry, let me finish — what I meant was..."],
                "wpm": 130,
                "filler": "≤1/min",
            },
            {
                "d": 27,
                "theme": "Natural Fillers & Flow",
                "persona": "alex",
                "mode": "debate",
                "aiLine": "Even I say 'well, actually' sometimes — use it on purpose, not by accident.",
                "instruction": "Free-talk for 1 minute, deliberately using 2 natural connectors instead of silence.",
                "phrasesA": ["Well, actually...", "You know, ...", "That said..."],
                "phrasesB": ["So...", "Basically..."],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": False,
                "script": ["Alex: What do you think about AI in classrooms?", "You: Well, actually, I think it depends on the age group."],
                "wpm": 132,
                "filler": "Controlled use",
            },
            {
                "d": 28,
                "theme": "Milestone: Group Discussion, All 4 Voices",
                "persona": "panel",
                "mode": "milestone",
                "aiLine": "Four perspectives, one topic. Hold your ground.",
                "instruction": "Join a 3-minute unscripted group discussion with all 4 AI partners. Speak at least 3 times.",
                "phrasesA": ["(no scaffold — speak freely)"],
                "phrasesB": ["Use any phrases from Week 4"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": True,
                "script": ["Rohan: Let's structure the debate first.", "Alex: Or let's just dive in — what do you think?"],
                "wpm": 134,
                "filler": "Minimal",
                "milestoneReport": True,
            },
        ],
    },
    {
        "title": "Test Match · Capstone",
        "range": "Days 29–30",
        "days": [
            {
                "d": 29,
                "theme": "Mixed Review: Surprise Panel",
                "persona": "panel",
                "mode": "group",
                "aiLine": "Three scenarios, zero warning. Let's see everything you've built.",
                "instruction": "Complete 3 surprise scenarios pulled from Weeks 1–4, back to back, no prep between them.",
                "phrasesA": ["(no scaffold — speak freely)"],
                "phrasesB": ["Use any phrase from the whole program"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": True,
                "script": ["Riya: Scenario 1 — introduce yourself to a new colleague.", "You: (free response, then Alex jumps in with Scenario 2)"],
                "wpm": 135,
                "filler": "0–1/min",
            },
            {
                "d": 30,
                "theme": "Final Certification: 1:1 Debate vs Alex",
                "persona": "alex",
                "mode": "milestone",
                "aiLine": "Last round. Convince me you've changed my mind.",
                "instruction": "Debate Alex for 3 minutes on a topic of his choice. This session generates your final certificate.",
                "phrasesA": ["(no scaffold — speak freely)"],
                "phrasesB": ["Use any phrase from the whole program"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": True,
                "script": ["Alex: Final round — is remote learning as effective as in-person?", "You: (free 3-minute debate)"],
                "wpm": 135,
                "filler": "0 Filler",
                "milestoneReport": True,
            },
        ],
    },
]


# ---------------------------------------------------------------------------
# TRACK B — "FROM SCRATCH" (30 days)
# For true beginners with little/no English. Listening/recognition comes
# before production. Text stays visible on screen and fades out by Week 4.
# Feeds directly into Track A Day 1 at the end of Week 5.
# ---------------------------------------------------------------------------

TRACK_B_WEEKS: List[Dict[str, Any]] = [
    {
        "title": "Sounds & Survival",
        "range": "Days 1–6",
        "days": [
            {
                "d": 1,
                "theme": "Greetings & Sounds",
                "persona": "riya",
                "mode": "echo",
                "aiLine": "Hi! Today we only listen and repeat. No pressure to create your own sentence yet.",
                "instruction": "Listen to each greeting, watch the mouth-shape guide, and repeat it 3 times.",
                "phrasesA": [],
                "phrasesB": ["Hello", "Hi", "Good morning", "Thank you", "Please"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "Hello. Good morning. Thank you.",
                "moodCheckIn": True,
                "textVisibleOnScreen": True,
                "script": ["Riya: Hello!", "You: Hello!"],
                "wpm": 50,
                "filler": "n/a",
            },
            {
                "d": 2,
                "theme": "Numbers 1–20",
                "persona": "riya",
                "mode": "echo",
                "aiLine": "Numbers are everywhere — let's get comfortable with them first.",
                "instruction": "Repeat numbers 1–20 after Riya. Then try counting alone without listening first.",
                "phrasesA": [],
                "phrasesB": ["One", "Two", "Three", "...", "Twenty"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "One, two, three, four, five.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Riya: One, two, three...", "You: One, two, three..."],
                "wpm": 50,
                "filler": "n/a",
            },
            {
                "d": 3,
                "theme": "Yes / No / Polite Words",
                "persona": "riya",
                "mode": "echo",
                "aiLine": "These small words unlock most conversations.",
                "instruction": "Repeat: Yes, No, Please, Thank you, Sorry, Excuse me. Then match each word to a picture.",
                "phrasesA": [],
                "phrasesB": ["Yes", "No", "Please", "Sorry", "Excuse me"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "Yes, please. No, thank you.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Riya: Yes, please.", "You: Yes, please."],
                "wpm": 52,
                "filler": "n/a",
            },
            {
                "d": 4,
                "theme": "This Is / That Is",
                "persona": "riya",
                "mode": "echo",
                "aiLine": "Let's name the things around you.",
                "instruction": "Look around you. Point at 5 objects and repeat 'This is a ___' after Riya for each.",
                "phrasesA": [],
                "phrasesB": ["This is a...", "That is a..."],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "This is a chair. This is a phone.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Riya: This is a chair.", "You: This is a chair."],
                "wpm": 52,
                "filler": "n/a",
            },
            {
                "d": 5,
                "theme": "Feelings (Simple)",
                "persona": "riya",
                "mode": "echo",
                "aiLine": "Now let's name how you feel — just one word at a time.",
                "instruction": "Repeat: happy, sad, tired, hungry, hot, cold. Point to the face that matches each one.",
                "phrasesA": [],
                "phrasesB": ["I am happy", "I am tired", "I am hungry"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "I am happy. I am tired.",
                "moodCheckIn": True,
                "textVisibleOnScreen": True,
                "script": ["Riya: I am happy.", "You: I am happy."],
                "wpm": 54,
                "filler": "n/a",
            },
            {
                "d": 6,
                "theme": "Milestone: First Words Check",
                "persona": "riya",
                "mode": "milestone",
                "aiLine": "Let's see everything you've picked up this week — no new words today, just review.",
                "instruction": "Riya will say 10 words from this week in random order. Repeat each one back correctly.",
                "phrasesA": [],
                "phrasesB": ["Review all Week 1 words"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": True,
                "textVisibleOnScreen": True,
                "script": ["Riya: Ready? Let's review together.", "You: (repeat each word)"],
                "wpm": 54,
                "filler": "n/a",
                "milestoneReport": True,
            },
        ],
    },
    {
        "title": "Word to Phrase",
        "range": "Days 7–12",
        "days": [
            {
                "d": 7,
                "theme": "Picture Word Match",
                "persona": "riya",
                "mode": "recognition",
                "aiLine": "See it, say it. Let's connect pictures to words out loud.",
                "instruction": "You'll see a picture. Say the word for it out loud before Riya reveals the answer.",
                "phrasesA": [],
                "phrasesB": ["Apple", "Water", "Book", "Car", "House"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "Apple. Water. Book.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Riya: What is this?", "You: Apple."],
                "wpm": 56,
                "filler": "n/a",
            },
            {
                "d": 8,
                "theme": "Two-Word Answers",
                "persona": "riya",
                "mode": "production",
                "aiLine": "You don't need full sentences yet — two words is a win.",
                "instruction": "Answer each question with just 2 words. Grammar doesn't need to be perfect.",
                "phrasesA": [],
                "phrasesB": ["Red apple", "I hungry", "Very hot", "So tired"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "Red apple. I hungry.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Riya: How do you feel?", "You: I hungry."],
                "wpm": 56,
                "filler": "n/a",
            },
            {
                "d": 9,
                "theme": "TPR Commands",
                "persona": "riya",
                "mode": "production",
                "aiLine": "Move your body while you speak — it helps the words stick.",
                "instruction": "Riya gives a command. Act it out AND repeat it out loud at the same time.",
                "phrasesA": [],
                "phrasesB": ["Stand up", "Sit down", "Point to the door", "Touch your head"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "Stand up. Sit down.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Riya: Stand up!", "You: (stands up) Stand up."],
                "wpm": 58,
                "filler": "n/a",
            },
            {
                "d": 10,
                "theme": "Family Words",
                "persona": "riya",
                "mode": "production",
                "aiLine": "Let's name your people in short phrases.",
                "instruction": "Say 'My ___' for 5 family members (mother, father, brother, sister, friend).",
                "phrasesA": [],
                "phrasesB": ["My mother", "My father", "My friend"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "My mother. My friend.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Riya: Tell me about your family.", "You: My mother. My friend."],
                "wpm": 58,
                "filler": "n/a",
            },
            {
                "d": 11,
                "theme": "Colors & Objects",
                "persona": "riya",
                "mode": "production",
                "aiLine": "Combine what you've learned — color plus object.",
                "instruction": "Describe 5 objects around you using 'color + object' (e.g. 'blue shirt').",
                "phrasesA": [],
                "phrasesB": ["Blue shirt", "Black bag", "White wall"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "Blue shirt. Black bag.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Riya: What color is your shirt?", "You: Blue shirt."],
                "wpm": 60,
                "filler": "n/a",
            },
            {
                "d": 12,
                "theme": "Milestone: 10 Two-Word Phrases",
                "persona": "riya",
                "mode": "milestone",
                "aiLine": "Show me 10 two-word phrases, back to back, without stopping.",
                "instruction": "Say 10 two-word phrases in a row from anything you've learned this week.",
                "phrasesA": [],
                "phrasesB": ["Review Week 2 phrases"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": True,
                "textVisibleOnScreen": True,
                "script": ["Riya: Your turn — 10 in a row!", "You: Red apple, blue shirt, my mother..."],
                "wpm": 60,
                "filler": "n/a",
                "milestoneReport": True,
            },
        ],
    },
    {
        "title": "First Sentences",
        "range": "Days 13–18",
        "days": [
            {
                "d": 13,
                "theme": "Sentence Builder: Present Tense",
                "persona": "riya",
                "mode": "production",
                "aiLine": "Let's stack words into your first real sentences.",
                "instruction": "Use the word tiles on screen to build 3 sentences, then say each one out loud.",
                "phrasesA": [],
                "phrasesB": ["I eat rice", "I go to work", "I drink water"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "I eat rice. I go to work.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Riya: What do you eat?", "You: I eat rice."],
                "wpm": 62,
                "filler": "n/a",
            },
            {
                "d": 14,
                "theme": "Either/Or Questions",
                "persona": "riya",
                "mode": "production",
                "aiLine": "Choosing between two options is easier than open questions — let's build confidence here.",
                "instruction": "Answer 6 either/or questions in full short sentences ('I like tea' not just 'tea').",
                "phrasesA": [],
                "phrasesB": ["I like...", "I prefer..."],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "I like tea. I prefer rice.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Riya: Tea or coffee?", "You: I like tea."],
                "wpm": 62,
                "filler": "n/a",
            },
            {
                "d": 15,
                "theme": "My Day (Present Tense Chain)",
                "persona": "riya",
                "mode": "production",
                "aiLine": "Let's chain 3 sentences together about your day.",
                "instruction": "Say 3 sentences in a row about today using 'I' + verb. Text stays on screen if you need it.",
                "phrasesA": [],
                "phrasesB": ["I wake up", "I eat breakfast", "I go to work"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "I wake up. I eat breakfast. I go to work.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Riya: Tell me about today.", "You: I wake up. I eat breakfast."],
                "wpm": 64,
                "filler": "n/a",
            },
            {
                "d": 16,
                "theme": "Simple Negatives",
                "persona": "riya",
                "mode": "production",
                "aiLine": "Now let's say what's NOT true.",
                "instruction": "Practice 5 sentences using 'I don't' or 'I am not.'",
                "phrasesA": [],
                "phrasesB": ["I don't like...", "I am not hungry"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "I don't like coffee. I am not tired.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Riya: Do you like coffee?", "You: I don't like coffee."],
                "wpm": 64,
                "filler": "n/a",
            },
            {
                "d": 17,
                "theme": "Simple Questions to Ask",
                "persona": "riya",
                "mode": "production",
                "aiLine": "Your turn to ask — even beginners can ask great questions.",
                "instruction": "Ask Riya 3 simple questions: What is your name? Where are you from? How are you?",
                "phrasesA": [],
                "phrasesB": ["What is your name?", "How are you?"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "What is your name? How are you?",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["You: What is your name?", "Riya: I'm Riya! How are you?"],
                "wpm": 66,
                "filler": "n/a",
            },
            {
                "d": 18,
                "theme": "Milestone: 5 Sentences, Text Hidden",
                "persona": "riya",
                "mode": "milestone",
                "aiLine": "This time, the words won't be on screen. Trust what you know.",
                "instruction": "Say 5 simple sentences about yourself with no text support this time.",
                "phrasesA": [],
                "phrasesB": ["Review Week 3 sentence patterns"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": True,
                "textVisibleOnScreen": False,
                "script": ["Riya: Tell me 5 things about yourself.", "You: (free response, no text support)"],
                "wpm": 66,
                "filler": "n/a",
                "milestoneReport": True,
            },
        ],
    },
    {
        "title": "Everyday Situations",
        "range": "Days 19–24",
        "days": [
            {
                "d": 19,
                "theme": "Greeting a Stranger",
                "persona": "rohan",
                "mode": "roleplay",
                "aiLine": "Let's practice a real situation — meeting someone new.",
                "instruction": "Roleplay a short greeting with Rohan. Script stays visible, but try saying it before reading.",
                "phrasesA": [],
                "phrasesB": ["Hello, nice to meet you", "How are you?"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "Hello, nice to meet you.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Rohan: Hello, nice to meet you.", "You: Hello, nice to meet you too."],
                "wpm": 68,
                "filler": "n/a",
            },
            {
                "d": 20,
                "theme": "Shopping (Simple)",
                "persona": "rohan",
                "mode": "roleplay",
                "aiLine": "Let's go shopping — one step at a time.",
                "instruction": "Roleplay buying one item: ask the price, say okay or too expensive.",
                "phrasesA": [],
                "phrasesB": ["How much?", "Too expensive", "Okay, I'll take it"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "How much is this? Okay, I'll take it.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Rohan: This is 200 rupees.", "You: Okay, I'll take it."],
                "wpm": 68,
                "filler": "n/a",
            },
            {
                "d": 21,
                "theme": "Asking for Help",
                "persona": "rohan",
                "mode": "roleplay",
                "aiLine": "Asking for help is one of the most useful phrases you'll ever learn.",
                "instruction": "Practice 3 ways to ask for help in different situations (lost, confused, need directions).",
                "phrasesA": [],
                "phrasesB": ["Can you help me?", "I am lost", "Where is...?"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "Can you help me? I am lost.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Rohan: What's wrong?", "You: Can you help me? I am lost."],
                "wpm": 70,
                "filler": "n/a",
            },
            {
                "d": 22,
                "theme": "Fill-in-the-Blank Roleplay",
                "persona": "rohan",
                "mode": "roleplay",
                "aiLine": "Half the sentence is yours to fill in now.",
                "instruction": "Rohan starts a sentence, you complete it out loud in a roleplay ordering food.",
                "phrasesA": [],
                "phrasesB": ["I would like...", "Can I get..."],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "I would like... a coffee, please.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Rohan: What would you like to...", "You: ...order? I would like a coffee."],
                "wpm": 70,
                "filler": "n/a",
            },
            {
                "d": 23,
                "theme": "Talking About Your Day (Recap)",
                "persona": "rohan",
                "mode": "roleplay",
                "aiLine": "Let's combine everything — greeting, small talk, and your day.",
                "instruction": "Have a 1-minute guided conversation with Rohan covering greeting + how your day was.",
                "phrasesA": [],
                "phrasesB": ["My day was...", "I feel..."],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": "My day was good. I feel happy.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Rohan: How was your day?", "You: My day was good, thank you."],
                "wpm": 72,
                "filler": "n/a",
            },
            {
                "d": 24,
                "theme": "Milestone: 3 Roleplays, Text Fading",
                "persona": "rohan",
                "mode": "milestone",
                "aiLine": "Text will fade halfway through each roleplay today. Keep going even if it disappears.",
                "instruction": "Complete 3 short roleplays back-to-back. Text will fade out partway through each one.",
                "phrasesA": [],
                "phrasesB": ["Review Week 4 roleplays"],
                "rescuePhrases": BEGINNER_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": True,
                "textVisibleOnScreen": True,
                "script": ["Rohan: Let's do 3 roleplays together.", "You: (complete each one as text fades)"],
                "wpm": 72,
                "filler": "n/a",
                "milestoneReport": True,
            },
        ],
    },
    {
        "title": "Bridge to Track A",
        "range": "Days 25–30",
        "days": [
            {
                "d": 25,
                "theme": "Open Questions, Training Wheels On",
                "persona": "riya",
                "mode": "bridge",
                "aiLine": "Now let's try open questions — sentence starters are still here if you need them.",
                "instruction": "Answer 3 open questions (no yes/no). Sentence starters remain visible as a safety net.",
                "phrasesA": ["I think...", "For me, it's..."],
                "phrasesB": ["I like...", "Because..."],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "I think... my favorite food is rice.",
                "moodCheckIn": True,
                "textVisibleOnScreen": True,
                "script": ["Riya: What's your favorite food?", "You: I think... my favorite food is rice."],
                "wpm": 74,
                "filler": "≤7/min",
            },
            {
                "d": 26,
                "theme": "Longer Sentences, No Prep",
                "persona": "riya",
                "mode": "bridge",
                "aiLine": "Let's stretch a little — 2 connected sentences this time.",
                "instruction": "Answer with 2 connected sentences using 'and' or 'because.' No prep time.",
                "phrasesA": ["...and also...", "...because..."],
                "phrasesB": ["I like... and..."],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "I like rice, and I also like tea.",
                "moodCheckIn": False,
                "textVisibleOnScreen": True,
                "script": ["Riya: Tell me about your weekend.", "You: I rested, and I also visited my family."],
                "wpm": 76,
                "filler": "≤7/min",
            },
            {
                "d": 27,
                "theme": "First Unscripted 30 Seconds",
                "persona": "riya",
                "mode": "bridge",
                "aiLine": "This is your first time with zero script. You're more ready than you think.",
                "instruction": "Talk for 30 seconds about your day with no script and no text on screen.",
                "phrasesA": [],
                "phrasesB": ["Use anything you've learned"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": True,
                "textVisibleOnScreen": False,
                "script": ["Riya: Just talk to me for 30 seconds — anything at all.", "You: (free response)"],
                "wpm": 78,
                "filler": "≤7/min",
            },
            {
                "d": 28,
                "theme": "Meet Your Rescue Phrases",
                "persona": "riya",
                "mode": "bridge",
                "aiLine": "Before you graduate, let's learn the phrases that will carry you through Track A.",
                "instruction": "Same as Day 0 of Track A — learn and repeat your rescue phrases. These are your new safety net.",
                "phrasesA": [],
                "phrasesB": [],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": "Give me a sec... Let me think about that...",
                "moodCheckIn": True,
                "textVisibleOnScreen": True,
                "script": ["Riya: If you ever blank, just say 'Give me a sec.'", "You: (repeat each rescue phrase)"],
                "wpm": 78,
                "filler": "n/a",
            },
            {
                "d": 29,
                "theme": "Mixed Review",
                "persona": "rohan",
                "mode": "bridge",
                "aiLine": "Let's put it all together — greetings, questions, roleplay, opinions.",
                "instruction": "Complete a mixed 2-minute session touching greetings, one roleplay, and one open question.",
                "phrasesA": ["I think...", "For me..."],
                "phrasesB": ["Review all tracks"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": False,
                "textVisibleOnScreen": False,
                "script": ["Rohan: Let's mix it up today.", "You: (respond across greeting, roleplay, opinion)"],
                "wpm": 80,
                "filler": "≤6/min",
            },
            {
                "d": 30,
                "theme": "Milestone: Graduate to Track A",
                "persona": "riya",
                "mode": "milestone",
                "aiLine": "You've come so far. Tomorrow, you start Track A — Day 1, Introduce Yourself, alongside learners who started right where you are now.",
                "instruction": "Introduce yourself for 30 seconds, freely, no text. This becomes your entry recording into Track A.",
                "phrasesA": [],
                "phrasesB": ["Use anything you've learned"],
                "rescuePhrases": DEFAULT_RESCUE_PHRASES,
                "shadowLine": None,
                "moodCheckIn": True,
                "textVisibleOnScreen": False,
                "script": ["Riya: Introduce yourself to me one more time.", "You: (free 30-second response)"],
                "wpm": 80,
                "filler": "≤6/min",
                "milestoneReport": True,
                "graduatesToTrackA": True,
            },
        ],
    },
]


# Backwards-compatibility alias
WEEKS_DATA = TRACK_A_WEEKS

TRACKS: Dict[str, Dict[str, Any]] = {
    "track_a": {
        "id": "track_a",
        "name": "Unfreeze",
        "subtitle": "For learners who understand English but blank when speaking",
        "weeks": TRACK_A_WEEKS,
    },
    "track_b": {
        "id": "track_b",
        "name": "From Scratch",
        "subtitle": "For true beginners — builds into Track A automatically",
        "weeks": TRACK_B_WEEKS,
    },
}


def get_track(track_id: str) -> Optional[Dict[str, Any]]:
    """Return the full track object ('track_a' or 'track_b')."""
    return TRACKS.get(track_id)


def get_all_days(track_id: str) -> List[Dict[str, Any]]:
    """Flatten all days for a given track, in order."""
    track = get_track(track_id)
    if not track:
        return []
    days: List[Dict[str, Any]] = []
    for w in track["weeks"]:
        days.extend(w["days"])
    return days


def get_day_by_number(track_id: str, day_num: int) -> Optional[Dict[str, Any]]:
    """Get a specific day's data from a specific track."""
    for d in get_all_days(track_id):
        if d["d"] == day_num:
            return d
    return None


def get_week_for_day(track_id: str, day_num: int) -> Optional[Dict[str, Any]]:
    """Return the week block (title/range) that contains the given day number."""
    track = get_track(track_id)
    if not track:
        return None
    for w in track["weeks"]:
        if any(d["d"] == day_num for d in w["days"]):
            return w
    return None


def recommend_track(placement_result: str) -> str:
    """Simple placement-test router.

    placement_result: 'blank_on_speaking' | 'true_beginner'
    Use this at onboarding to route the user into the right track.
    """
    if placement_result == "true_beginner":
        return "track_b"
    return "track_a"


def is_graduation_day(track_id: str, day_num: int) -> bool:
    """True if completing this day should trigger the Track B -> Track A handoff."""
    day = get_day_by_number(track_id, day_num)
    return bool(day and day.get("graduatesToTrackA"))


def get_lightweight_day_display(day: Dict[str, Any], track_id: str = "track_a") -> Dict[str, Any]:
    """Derived display layer for UI rendering.

    Computes lightweight UI versions (short hook, short instruction, stat chips,
    primary phrase + remaining count, accordion flags) without modifying authored data.
    """
    ai_line = day.get("aiLine", "")

    # Extract short hook: first sentence or clause before ' — ' or '.'
    if " — " in ai_line:
        short_hook = ai_line.split(" — ")[0].strip() + "."
    elif "." in ai_line:
        short_hook = ai_line.split(".")[0].strip() + "."
    elif "!" in ai_line:
        short_hook = ai_line.split("!")[0].strip() + "!"
    elif "?" in ai_line:
        short_hook = ai_line.split("?")[0].strip() + "?"
    else:
        short_hook = ai_line

    instruction = day.get("instruction", "")
    # Short instruction: first sentence
    if "." in instruction:
        short_instruction = instruction.split(".")[0].strip() + "."
    else:
        short_instruction = instruction

    wpm = day.get("wpm")
    wpm_str = f"⏱️ {wpm} WPM" if wpm else "⏱️ Free Pace"
    filler = day.get("filler", "n/a")
    filler_str = f"🎯 {filler}"
    rescue_phrases = day.get("rescuePhrases") or []
    rescue_str = "🛟 Rescue on" if rescue_phrases else "🛟 Standard"

    track_key = track_id.lower()
    if track_key in ("track_a", "a"):
        phrases = day.get("phrasesA") or day.get("phrasesB") or []
    else:
        phrases = day.get("phrasesB") or day.get("phrasesA") or []

    primary_phrase = phrases[0] if phrases else None
    remaining_phrases_count = max(0, len(phrases) - 1)

    return {
        **day,
        "shortHook": short_hook,
        "shortInstruction": short_instruction,
        "statChips": [wpm_str, filler_str, rescue_str],
        "primaryPhrase": primary_phrase,
        "remainingPhrasesCount": remaining_phrases_count,
        "allPhrases": phrases,
        "hasFullAiLine": len(ai_line.strip()) > len(short_hook.strip()),
        "hasFullInstruction": len(instruction.strip()) > len(short_instruction.strip()),
        "hasSampleExchange": bool(day.get("script")),
        "hasShadow": bool(day.get("shadowLine")),
        "hasMoodCheckin": bool(day.get("moodCheckIn")),
    }